#!/usr/bin/env bash

set -euo pipefail
umask 077

die() {
  printf 'W38: %s\n' "$*" >&2
  exit 1
}

stop_pid_file() {
  local pid_file=$1
  local label=$2
  [[ -f "$pid_file" ]] || return 0
  local pid
  pid=$(<"$pid_file")
  [[ "$pid" =~ ^[0-9]+$ ]] || die "$label pid file is invalid"
  if kill -0 "$pid" >/dev/null 2>&1; then
    kill -TERM "$pid"
    for _ in $(seq 1 80); do
      kill -0 "$pid" >/dev/null 2>&1 || break
      sleep 0.25
    done
    kill -0 "$pid" >/dev/null 2>&1 && die "$label did not stop after SIGTERM"
  fi
}

stop_runtime() {
  local run_root=$1
  local state_file="$run_root/state/runtime.env"
  [[ -f "$state_file" ]] || die "runtime state is unavailable: $state_file"
  # The file is generated by this script and contains only validated paths and ports.
  # shellcheck disable=SC1090
  source "$state_file"
  stop_pid_file "$run_root/state/openclaw.pid" "OpenClaw Gateway"
  stop_pid_file "$run_root/state/vermory.pid" "Vermory service"
  if "$postgres_bin/pg_ctl" -D "$postgres_data" status >/dev/null 2>&1; then
    "$postgres_bin/pg_ctl" -D "$postgres_data" -m fast stop >/dev/null
  fi
  if [[ -L "$postgres_socket_link" ]]; then
    unlink "$postgres_socket_link"
  fi
  printf 'W38: stopped; retained external run root=%s\n' "$run_root"
}

hold_runtime() {
  local run_root=$1
  local state_file="$run_root/state/runtime.env"
  [[ -f "$state_file" ]] || die "runtime state is unavailable: $state_file"
  # shellcheck disable=SC1090
  source "$state_file"
  "$postgres_bin/pg_ctl" -D "$postgres_data" status >/dev/null 2>&1 || die "PostgreSQL is not running"
  local service_runner="$run_root/bin/vermory-service-w38"
  local gateway_runner="$run_root/bin/openclaw-gateway-w38"
  [[ -x "$service_runner" && -x "$gateway_runner" ]] || die "runtime launchers are unavailable"

  "$service_runner" >>"$run_root/evidence/raw/vermory-service.log" 2>&1 &
  local vermory_pid=$!
  printf '%s\n' "$vermory_pid" >"$run_root/state/vermory.pid"
  "$gateway_runner" >>"$run_root/evidence/raw/openclaw-gateway.log" 2>&1 &
  local openclaw_pid=$!
  printf '%s\n' "$openclaw_pid" >"$run_root/state/openclaw.pid"

  hold_cleanup() {
    set +e
    kill -TERM "$openclaw_pid" "$vermory_pid" >/dev/null 2>&1
    wait "$openclaw_pid" "$vermory_pid" >/dev/null 2>&1
  }
  trap hold_cleanup EXIT
  trap 'exit 0' HUP INT TERM
  printf 'W38: holding Vermory and OpenClaw processes for run=%s\n' "$run_root"
  while kill -0 "$vermory_pid" >/dev/null 2>&1 && kill -0 "$openclaw_pid" >/dev/null 2>&1; do
    sleep 1
  done
  die "a held W38 process exited; inspect the retained service logs"
}

if [[ $# -ge 1 && "$1" == "stop" ]]; then
  [[ $# -eq 2 ]] || die "usage: $0 stop /Volumes/JSData/path/to/run"
  stop_runtime "$2"
  exit 0
fi

if [[ $# -ge 1 && "$1" == "hold" ]]; then
  [[ $# -eq 2 ]] || die "usage: $0 hold /Volumes/JSData/path/to/run"
  hold_runtime "$2"
  exit 0
fi

if [[ $# -ne 4 || "$1" != "start" ]]; then
  die "usage: $0 start /path/to/repository /path/to/vermory /Volumes/JSData/path/to/run"
fi

repo_root=$(cd "$2" && pwd)
binary=$(cd "$(dirname "$3")" && pwd)/$(basename "$3")
run_root=$4
case "$run_root" in
  /Volumes/JSData/*) ;;
  *) die "the W38 run root must be on /Volumes/JSData" ;;
esac
[[ -x "$binary" ]] || die "candidate Vermory binary is not executable"
[[ -f "$repo_root/runtime/cases/W38-official-openclaw-webchat/case.json" ]] || die "W38 case is unavailable"

plugin_dir="$repo_root/integrations/openclaw"
openclaw_cli="$plugin_dir/node_modules/.bin/openclaw"
bundled_plugins="$plugin_dir/node_modules/openclaw/dist/extensions"
[[ -x "$openclaw_cli" ]] || die "OpenClaw CLI is unavailable"
[[ -f "$plugin_dir/dist/index.js" ]] || die "the Vermory OpenClaw plugin has not been built"
[[ -d "$bundled_plugins" ]] || die "the pinned OpenClaw bundled plugin directory is unavailable"

grok_binary=${VERMORY_W38_GROK_BINARY:-/opt/homebrew/bin/grok}
grok_auth=${VERMORY_W38_GROK_AUTH:-}
[[ -x "$grok_binary" ]] || die "Grok CLI is unavailable"
[[ -f "$grok_auth" ]] || die "VERMORY_W38_GROK_AUTH must identify an authenticated external-volume auth file"
case "$(cd "$(dirname "$grok_auth")" && pwd)/$(basename "$grok_auth")" in
  /Volumes/JSData/*) ;;
  *) die "Grok auth source must be on /Volumes/JSData" ;;
esac

postgres_bin=${VERMORY_POSTGRES_BIN:-/opt/homebrew/Cellar/postgresql@18/18.4/bin}
for tool in initdb pg_ctl psql createdb; do
  [[ -x "$postgres_bin/$tool" ]] || die "PostgreSQL tool is unavailable: $postgres_bin/$tool"
done
for tool in jq curl openssl shasum lsof; do
  command -v "$tool" >/dev/null || die "$tool is required"
done

vermory_port=${VERMORY_W38_VERMORY_PORT:-18839}
openclaw_port=${VERMORY_W38_OPENCLAW_PORT:-18838}
postgres_port=${VERMORY_W38_POSTGRES_PORT:-55438}
for port in "$vermory_port" "$openclaw_port" "$postgres_port"; do
  [[ "$port" =~ ^[0-9]+$ ]] || die "ports must be numeric"
  ((port >= 1 && port <= 65535)) || die "port is outside 1..65535: $port"
  if lsof -nP -iTCP:"$port" -sTCP:LISTEN -t >/dev/null 2>&1; then
    die "port is already occupied: $port"
  fi
done

[[ ! -e "$run_root" ]] || die "run root already exists; retain it and choose a new attempt path"
mkdir -p \
  "$run_root/bin" \
  "$run_root/cache" \
  "$run_root/evidence/raw" \
  "$run_root/grok-app" \
  "$run_root/home" \
  "$run_root/openclaw/config" \
  "$run_root/openclaw/state" \
  "$run_root/openclaw/workspace" \
  "$run_root/postgres/socket" \
  "$run_root/secrets" \
  "$run_root/state" \
  "$run_root/tmp"
chmod 0700 "$run_root" "$run_root/secrets" "$run_root/openclaw/state" "$run_root/tmp"

raw_root="$run_root/evidence/raw"
postgres_data="$run_root/postgres/data"
short_id=$(printf '%s' "$run_root" | shasum -a 256 | awk '{print substr($1,1,10)}')
postgres_socket_link="/tmp/vermory-w38-$short_id"
[[ ! -e "$postgres_socket_link" && ! -L "$postgres_socket_link" ]] || die "temporary PostgreSQL socket link already exists"
ln -s "$run_root/postgres/socket" "$postgres_socket_link"

cleanup_failed_start() {
  local status=$?
  if ((status != 0)); then
    set +e
    stop_pid_file "$run_root/state/openclaw.pid" "OpenClaw Gateway"
    stop_pid_file "$run_root/state/vermory.pid" "Vermory service"
    "$postgres_bin/pg_ctl" -D "$postgres_data" -m fast stop >/dev/null 2>&1
    [[ -L "$postgres_socket_link" ]] && unlink "$postgres_socket_link"
    printf 'W38: start failed; retained external attempt=%s\n' "$run_root" >&2
  fi
  exit "$status"
}
trap cleanup_failed_start EXIT HUP INT TERM

"$postgres_bin/initdb" -D "$postgres_data" --username=postgres --auth-local=trust --auth-host=scram-sha-256 --no-instructions >"$raw_root/initdb.log"
"$postgres_bin/pg_ctl" -D "$postgres_data" -l "$raw_root/postgres.log" \
  -o "-p $postgres_port -k $postgres_socket_link -c listen_addresses=127.0.0.1 -c unix_socket_permissions=0700" start >/dev/null
for _ in $(seq 1 80); do
  if "$postgres_bin/psql" -h "$postgres_socket_link" -p "$postgres_port" -U postgres -d postgres -Atc 'SELECT 1' >/dev/null 2>&1; then
    break
  fi
  sleep 0.25
done
"$postgres_bin/psql" -h "$postgres_socket_link" -p "$postgres_port" -U postgres -d postgres -Atc 'SELECT 1' >/dev/null || die "PostgreSQL did not become ready"

database_name="vermory_w38_$short_id"
runtime_role="vermory_w38_${short_id}_runtime"
tenant_id="w38-official-webchat-$short_id"
runtime_password=$(openssl rand -hex 24)
gateway_token=$(openssl rand -hex 32)
admin_url="postgresql:///$database_name?host=$postgres_socket_link&port=$postgres_port&user=postgres&sslmode=disable"
runtime_url="postgresql://$runtime_role:$runtime_password@127.0.0.1:$postgres_port/$database_name?sslmode=disable"
printf '%s' "$runtime_password" >"$run_root/secrets/runtime-password"
printf '%s' "$runtime_url" >"$run_root/secrets/runtime-url"
printf '%s' "$gateway_token" >"$run_root/secrets/gateway-token"

"$postgres_bin/psql" -h "$postgres_socket_link" -p "$postgres_port" -U postgres -d postgres -v ON_ERROR_STOP=1 -qAtc \
  "CREATE ROLE $runtime_role LOGIN PASSWORD '$runtime_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS" >/dev/null
"$postgres_bin/createdb" -h "$postgres_socket_link" -p "$postgres_port" -U postgres "$database_name"
"$binary" database migrate --database-url "$admin_url" >"$raw_root/migrate.json"
"$binary" database grant-runtime --database-url "$admin_url" --role "$runtime_role" >"$raw_root/grant-runtime.json"
"$binary" database compatibility --database-url "$runtime_url" >"$raw_root/compatibility.json"
jq -e '.status == "compatible" and .schema_version == 25' "$raw_root/compatibility.json" >/dev/null

expires_at=$(date -u -v+1d '+%Y-%m-%dT%H:%M:%SZ')
issue_token() {
  local role=$1
  local subject=$2
  local receipt="$run_root/secrets/$role-token-receipt.json"
  "$binary" identity token issue \
    --database-url "$admin_url" \
    --operation-id "w38-$role-token-$short_id" \
    --tenant-id "$tenant_id" \
    --subject-id "$subject" \
    --role "$role" \
    --expires-at "$expires_at" >"$receipt"
  jq -er '.token' "$receipt" >"$run_root/secrets/$role-token"
  jq 'del(.token)' "$receipt" >"$raw_root/$role-token-receipt.json"
}
issue_token client w38-openclaw-client
issue_token operator w38-openclaw-operator

grok_runtime="$run_root/grok-app/grok"
mkdir -p "$grok_runtime/home" "$grok_runtime/state"
/usr/bin/install -m 0600 "$grok_auth" "$grok_runtime/state/auth.json"
grok_environment_wrapper="$grok_runtime/grok-vermory-environment"
grok_wrapper="$grok_runtime/grok-vermory-isolated"
grok_proxy=${VERMORY_W38_GROK_PROXY_URL:-http://127.0.0.1:6152}
cat >"$grok_environment_wrapper" <<EOF
#!/bin/sh
set -eu
export HOME="$grok_runtime/home"
export GROK_HOME="$grok_runtime/state"
export GROK_MEMORY=0
export GROK_SUBAGENTS=0
export GROK_WEB_FETCH=0
export GROK_FEEDBACK_ENABLED=0
export HTTP_PROXY="$grok_proxy"
export HTTPS_PROXY="$grok_proxy"
export NO_PROXY="127.0.0.1,localhost"
export RUST_LOG=error
unset XAI_API_KEY GROK_AUTH_PROVIDER_COMMAND GROK_DEPLOYMENT_KEY
exec "$grok_binary" "\$@"
EOF
chmod 0700 "$grok_environment_wrapper"
cat >"$grok_wrapper" <<EOF
#!/bin/sh
set -eu
exec "$grok_environment_wrapper" \
  --no-memory \
  --no-plan \
  --no-subagents \
  --disable-web-search \
  --tools todo_write \
  --disallowed-tools todo_write,update_goal,search_tool,use_tool,CallMcpTool,Agent \
  --permission-mode dontAsk \
  --max-turns 1 \
  --verbatim \
  "\$@"
EOF
chmod 0700 "$grok_wrapper"
grok_version=$("$grok_wrapper" --version 2>&1 | head -1)
grok_sha256=$(shasum -a 256 "$grok_binary" | awk '{print $1}')
printf 'runtime=grok state=external auth=protected version=%s sha256=%s\n' "$grok_version" "$grok_sha256" >"$raw_root/grok-install.log"

openclaw_config="$run_root/openclaw/config/openclaw.json"
jq -n \
  --arg workspace "$run_root/openclaw/workspace" \
  --arg pluginDir "$plugin_dir" \
  --arg grokCommand "$grok_wrapper" \
  --arg vermoryBaseURL "http://127.0.0.1:$vermory_port" \
  --rawfile gatewayToken "$run_root/secrets/gateway-token" \
  --argjson gatewayPort "$openclaw_port" \
  '{
    gateway:{
      mode:"local",
      bind:"loopback",
      port:$gatewayPort,
      auth:{mode:"token",token:$gatewayToken}
    },
    agents:{defaults:{
      workspace:$workspace,
      model:{primary:"grok-cli/grok-4.5"},
      models:{"grok-cli/grok-4.5":{}},
      cliBackends:{
        "grok-cli":{
          command:$grokCommand,
          args:["--output-format","json","--single","{prompt}"],
          output:"json",
          input:"arg",
          modelArg:"--model",
          sessionMode:"none",
          serialize:true,
          clearEnv:["XAI_API_KEY","GROK_AUTH_PROVIDER_COMMAND","GROK_DEPLOYMENT_KEY"]
        }
      }
    }},
    plugins:{
      load:{paths:[$pluginDir]},
      allow:["vermory"],
      entries:{
        vermory:{
          enabled:true,
          hooks:{
            allowPromptInjection:true,
            allowConversationAccess:true,
            timeouts:{before_prompt_build:15000,after_tool_call:15000,agent_end:30000}
          },
          config:{baseUrl:$vermoryBaseURL,timeoutMs:10000,toolAllowlist:[]}
        }
      }
    }
  }' >"$openclaw_config"
chmod 0600 "$openclaw_config"

openclaw_wrapper="$run_root/bin/openclaw-w38"
cat >"$openclaw_wrapper" <<EOF
#!/bin/sh
set -eu
export HOME="$run_root/home"
export TMPDIR="$run_root/tmp"
export XDG_CACHE_HOME="$run_root/cache"
export OPENCLAW_STATE_DIR="$run_root/openclaw/state"
export OPENCLAW_CONFIG_PATH="$openclaw_config"
export OPENCLAW_BUNDLED_PLUGINS_DIR="$bundled_plugins"
exec "$openclaw_cli" "\$@"
EOF
chmod 0755 "$openclaw_wrapper"

"$openclaw_wrapper" config validate >"$raw_root/openclaw-config-validation.txt"
"$openclaw_wrapper" plugins inspect vermory --runtime --json >"$raw_root/vermory-plugin-runtime.json"
jq -e '
  .plugin.id == "vermory" and
  .plugin.status == "loaded" and
  (.commands | index("vermory") != null) and
  ([.typedHooks[]?.name] | index("before_prompt_build") != null) and
  ([.typedHooks[]?.name] | index("agent_end") != null)
' "$raw_root/vermory-plugin-runtime.json" >/dev/null

service_runner="$run_root/bin/vermory-service-w38"
cat >"$service_runner" <<EOF
#!/bin/sh
set -eu
runtime_url=\$(cat "$run_root/secrets/runtime-url")
export HOME="$run_root/home"
export TMPDIR="$run_root/tmp"
export VERMORY_DATABASE_URL="\$runtime_url"
export VERMORY_LISTEN="127.0.0.1:$vermory_port"
export VERMORY_PROVIDER=mock
export VERMORY_MODEL=w38-openclaw-host-runtime
exec "$binary" serve
EOF
chmod 0700 "$service_runner"

gateway_runner="$run_root/bin/openclaw-gateway-w38"
cat >"$gateway_runner" <<EOF
#!/bin/sh
set -eu
export VERMORY_API_TOKEN=\$(cat "$run_root/secrets/client-token")
export VERMORY_OPERATOR_API_TOKEN=\$(cat "$run_root/secrets/operator-token")
exec "$openclaw_wrapper" gateway run --port "$openclaw_port" --ws-log full --cli-backend-logs
EOF
chmod 0700 "$gateway_runner"

nohup "$service_runner" >"$raw_root/vermory-service.log" 2>&1 &
vermory_pid=$!
printf '%s\n' "$vermory_pid" >"$run_root/state/vermory.pid"
client_token=$(<"$run_root/secrets/client-token")
for _ in $(seq 1 80); do
  code=$(curl --noproxy '*' -s -o /dev/null -w '%{http_code}' \
    -H "Authorization: Bearer $client_token" "http://127.0.0.1:$vermory_port/v1/session" || true)
  [[ "$code" == "200" ]] && break
  sleep 0.25
done
[[ "$code" == "200" ]] || die "authenticated Vermory service did not become ready"

nohup "$gateway_runner" >"$raw_root/openclaw-gateway.log" 2>&1 &
openclaw_pid=$!
printf '%s\n' "$openclaw_pid" >"$run_root/state/openclaw.pid"
for _ in $(seq 1 120); do
  if "$openclaw_wrapper" gateway health --json >"$raw_root/openclaw-health.json" 2>/dev/null; then
    break
  fi
  sleep 0.25
done
[[ -s "$raw_root/openclaw-health.json" ]] || die "OpenClaw Gateway did not become ready"

cat >"$run_root/state/runtime.env" <<EOF
postgres_bin='$postgres_bin'
postgres_data='$postgres_data'
postgres_socket_link='$postgres_socket_link'
postgres_port='$postgres_port'
vermory_port='$vermory_port'
openclaw_port='$openclaw_port'
tenant_id='$tenant_id'
admin_url='$admin_url'
runtime_role='$runtime_role'
openclaw_wrapper='$openclaw_wrapper'
grok_wrapper='$grok_wrapper'
grok_formation_wrapper='$grok_environment_wrapper'
EOF
chmod 0600 "$run_root/state/runtime.env"

jq -n \
  --arg case_id W38-official-openclaw-webchat \
  --arg tenant_id "$tenant_id" \
  --arg openclaw_version "$("$openclaw_wrapper" --version | head -1)" \
  --arg grok_version "$grok_version" \
  --argjson schema_version "$(jq '.schema_version' "$raw_root/compatibility.json")" \
  --argjson vermory_port "$vermory_port" \
  --argjson openclaw_port "$openclaw_port" \
  '{
    schema_version:"w38-runtime-start/v1",
    case_id:$case_id,
    status:"running",
    tenant_id:$tenant_id,
    database_schema:$schema_version,
    openclaw_version:$openclaw_version,
    grok_version:$grok_version,
    listeners:{vermory_loopback_port:$vermory_port,openclaw_loopback_port:$openclaw_port},
    storage:{external_volume:true,local_home_used:false},
    credentials_in_public_summary:false
  }' >"$run_root/runtime-start.json"

runtime_password=''
runtime_url=''
gateway_token=''
client_token=''
trap - EXIT HUP INT TERM
printf 'W38: running on external volume; summary=%s\n' "$run_root/runtime-start.json"
